# Generated by Django 5.1.3 on 2024-11-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=100)),
                ('sale_amount', models.FloatField()),
            ],
            options={
                'db_table': 'sales_data',
                'managed': False,
            },
        ),
    ]
